# Generated by Django 4.2.1 on 2023-05-16 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('info', models.TextField(default='')),
                ('img', models.CharField(default='', max_length=200)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
