# Generated by Django 4.1.7 on 2023-05-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='nome',
            new_name='name',
        ),
    ]
