# Generated by Django 4.2.1 on 2023-05-29 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_rename_data_event_date_rename_nome_event_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='EventUser',
        ),
    ]
